"""
Django settings for AI4MW_web project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"").strip("'")
        os.environ.setdefault(key, value)


def _load_yaml_file(yaml_path: Path) -> dict:
    if not yaml_path.exists():
        return {}
    parsed: dict[str, str] = {}
    for line in yaml_path.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or ":" not in raw:
            continue
        key, value = raw.split(":", 1)
        key = key.strip()
        value = value.strip().strip("\"").strip("'")
        if key:
            parsed[key] = value
    return parsed

def _get_env_int(key: str, default: int) -> int:
    raw = os.getenv(key)
    if raw is None or raw == "":
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def _get_env_float(key: str, default: float) -> float:
    raw = os.getenv(key)
    if raw is None or raw == "":
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def _get_env_bool(key: str, default: bool) -> bool:
    raw = os.getenv(key)
    if raw is None or raw == "":
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _get_env_list(key: str, default: list[str] | None = None) -> list[str]:
    raw = os.getenv(key)
    if raw is None or raw == "":
        return list(default or [])
    return [item.strip() for item in raw.split(",") if item.strip()]


def _get_env_json_dict(key: str, default: dict | None = None) -> dict:
    raw = os.getenv(key)
    if raw is None or raw == "":
        return dict(default or {})
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return dict(default or {})
    if not isinstance(parsed, dict):
        return dict(default or {})
    return {str(k): str(v) for k, v in parsed.items() if str(k).strip() and str(v).strip()}


_config_values = _load_yaml_file(BASE_DIR / "config.yaml")
_load_env_file(BASE_DIR / ".env")
for _key, _value in _config_values.items():
    os.environ.setdefault(_key, _value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-jt!*oh74)p3m@u4ox1(y^qvu%94-$ivdo9w(vp%hq(3u@@k89f",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_env_bool("DEBUG", True)

ALLOWED_HOSTS = _get_env_list("ALLOWED_HOSTS", ["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "llm_agent",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AI4MW_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AI4MW_web.wsgi.application"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME", "AI4MW_WEB"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5433"),
    }
}

LLM_CONFIG = {
    "NAME": "chat",
    "PROVIDER": os.getenv("LLM_PROVIDER", "openai"),
    "MODEL": os.getenv("LLM_MODEL", "gpt-4.1"),
    "API_BASE": os.getenv("LLM_API_BASE", "https://api.openai.com/v1"),
    "API_KEY": os.getenv("LLM_API_KEY", ""),
    "API_INTERFACE": os.getenv("LLM_API_INTERFACE", "chat_completions"),
    "API_INTERFACE_PREFERENCE": os.getenv(
        "LLM_API_INTERFACE_PREFERENCE",
        os.getenv("LLM_API_INTERFACE", "chat_completions"),
    ),
    "TEMPERATURE": _get_env_float("LLM_TEMPERATURE", 0.2),
    "CONNECT_TIMEOUT_SEC": _get_env_float("LLM_CONNECT_TIMEOUT_SEC", 10.0),
    "READ_TIMEOUT_SEC": _get_env_float("LLM_READ_TIMEOUT_SEC", 60.0),
    "STREAM_READ_TIMEOUT_SEC": _get_env_float("LLM_STREAM_READ_TIMEOUT_SEC", 300.0),
    "MAX_RETRIES": _get_env_int("LLM_MAX_RETRIES", 2),
    "INITIAL_RETRY_DELAY_SEC": _get_env_float("LLM_INITIAL_RETRY_DELAY_SEC", 1.0),
    "MAX_RETRY_DELAY_SEC": _get_env_float("LLM_MAX_RETRY_DELAY_SEC", 8.0),
    "POOL_MAXSIZE": _get_env_int("LLM_POOL_MAXSIZE", 10),
    "EXTRA_HEADERS": _get_env_json_dict("LLM_EXTRA_HEADERS_JSON", {}),
}

SUMMARY_LLM_CONFIG = {
    "NAME": "summary",
    "PROVIDER": os.getenv("SUMMARY_LLM_PROVIDER", LLM_CONFIG["PROVIDER"]),
    "MODEL": os.getenv("SUMMARY_LLM_MODEL", LLM_CONFIG["MODEL"]),
    "API_BASE": os.getenv("SUMMARY_LLM_API_BASE", LLM_CONFIG["API_BASE"]),
    "API_KEY": os.getenv("SUMMARY_LLM_API_KEY", LLM_CONFIG["API_KEY"]),
    "API_INTERFACE": os.getenv("SUMMARY_LLM_API_INTERFACE", LLM_CONFIG["API_INTERFACE"]),
    "API_INTERFACE_PREFERENCE": os.getenv(
        "SUMMARY_LLM_API_INTERFACE_PREFERENCE",
        LLM_CONFIG["API_INTERFACE_PREFERENCE"],
    ),
    "TEMPERATURE": _get_env_float("SUMMARY_LLM_TEMPERATURE", LLM_CONFIG["TEMPERATURE"]),
    "CONNECT_TIMEOUT_SEC": _get_env_float(
        "SUMMARY_LLM_CONNECT_TIMEOUT_SEC",
        LLM_CONFIG["CONNECT_TIMEOUT_SEC"],
    ),
    "READ_TIMEOUT_SEC": _get_env_float(
        "SUMMARY_LLM_READ_TIMEOUT_SEC",
        LLM_CONFIG["READ_TIMEOUT_SEC"],
    ),
    "STREAM_READ_TIMEOUT_SEC": _get_env_float(
        "SUMMARY_LLM_STREAM_READ_TIMEOUT_SEC",
        LLM_CONFIG["STREAM_READ_TIMEOUT_SEC"],
    ),
    "MAX_RETRIES": _get_env_int("SUMMARY_LLM_MAX_RETRIES", LLM_CONFIG["MAX_RETRIES"]),
    "INITIAL_RETRY_DELAY_SEC": _get_env_float(
        "SUMMARY_LLM_INITIAL_RETRY_DELAY_SEC",
        LLM_CONFIG["INITIAL_RETRY_DELAY_SEC"],
    ),
    "MAX_RETRY_DELAY_SEC": _get_env_float(
        "SUMMARY_LLM_MAX_RETRY_DELAY_SEC",
        LLM_CONFIG["MAX_RETRY_DELAY_SEC"],
    ),
    "POOL_MAXSIZE": _get_env_int("SUMMARY_LLM_POOL_MAXSIZE", LLM_CONFIG["POOL_MAXSIZE"]),
    "EXTRA_HEADERS": _get_env_json_dict(
        "SUMMARY_LLM_EXTRA_HEADERS_JSON",
        LLM_CONFIG["EXTRA_HEADERS"],
    ),
}

PAPER_SEARCH_LLM_CONFIG = {
    "NAME": "paper_search",
    "PROVIDER": os.getenv("PAPER_SEARCH_LLM_PROVIDER", LLM_CONFIG["PROVIDER"]),
    "MODEL": os.getenv("PAPER_SEARCH_LLM_MODEL", ""),
    "API_BASE": os.getenv("PAPER_SEARCH_LLM_API_BASE", LLM_CONFIG["API_BASE"]),
    "API_KEY": os.getenv("PAPER_SEARCH_LLM_API_KEY", LLM_CONFIG["API_KEY"]),
    "API_INTERFACE": os.getenv("PAPER_SEARCH_LLM_API_INTERFACE", LLM_CONFIG["API_INTERFACE"]),
    "API_INTERFACE_PREFERENCE": os.getenv(
        "PAPER_SEARCH_LLM_API_INTERFACE_PREFERENCE",
        LLM_CONFIG["API_INTERFACE_PREFERENCE"],
    ),
    "TEMPERATURE": _get_env_float("PAPER_SEARCH_LLM_TEMPERATURE", LLM_CONFIG["TEMPERATURE"]),
    "CONNECT_TIMEOUT_SEC": _get_env_float(
        "PAPER_SEARCH_LLM_CONNECT_TIMEOUT_SEC",
        LLM_CONFIG["CONNECT_TIMEOUT_SEC"],
    ),
    "READ_TIMEOUT_SEC": _get_env_float(
        "PAPER_SEARCH_LLM_READ_TIMEOUT_SEC",
        LLM_CONFIG["READ_TIMEOUT_SEC"],
    ),
    "STREAM_READ_TIMEOUT_SEC": _get_env_float(
        "PAPER_SEARCH_LLM_STREAM_READ_TIMEOUT_SEC",
        LLM_CONFIG["STREAM_READ_TIMEOUT_SEC"],
    ),
    "MAX_RETRIES": _get_env_int("PAPER_SEARCH_LLM_MAX_RETRIES", LLM_CONFIG["MAX_RETRIES"]),
    "INITIAL_RETRY_DELAY_SEC": _get_env_float(
        "PAPER_SEARCH_LLM_INITIAL_RETRY_DELAY_SEC",
        LLM_CONFIG["INITIAL_RETRY_DELAY_SEC"],
    ),
    "MAX_RETRY_DELAY_SEC": _get_env_float(
        "PAPER_SEARCH_LLM_MAX_RETRY_DELAY_SEC",
        LLM_CONFIG["MAX_RETRY_DELAY_SEC"],
    ),
    "POOL_MAXSIZE": _get_env_int("PAPER_SEARCH_LLM_POOL_MAXSIZE", LLM_CONFIG["POOL_MAXSIZE"]),
    "EXTRA_HEADERS": _get_env_json_dict(
        "PAPER_SEARCH_LLM_EXTRA_HEADERS_JSON",
        LLM_CONFIG["EXTRA_HEADERS"],
    ),
}

EMBED_CONFIG = {
    "PROVIDER": os.getenv("EMBED_PROVIDER", "openai"),
    "MODEL": os.getenv("EMBED_MODEL", "text-embedding-3-large"),
    "API_BASE": os.getenv("EMBED_API_BASE", "https://api.openai.com/v1"),
    "API_KEY": os.getenv("EMBED_API_KEY", ""),
    "DIM": _get_env_int("EMBED_DIM", 3072),
    "BATCH_SIZE": _get_env_int("EMBED_BATCH_SIZE", 64),
}

VLM_CONFIG = {
    "PROVIDER": os.getenv("VLM_PROVIDER", "openai"),
    "MODEL": os.getenv("VLM_MODEL", "gpt-4o-mini"),
    "API_BASE": os.getenv("VLM_API_BASE", "https://api.openai.com/v1"),
    "API_KEY": os.getenv("VLM_API_KEY", ""),
}

LINE_BUILD_CONFIG = {
    "BASE_URL": os.getenv("LINE_BUILD_BASE_URL", "http://localhost:8004"),
    "TIMEOUT_SEC": _get_env_int("LINE_BUILD_TIMEOUT_SEC", 120),
}

LLM_AGENT_TOOL_WORKSPACE = os.getenv("LLM_AGENT_TOOL_WORKSPACE", str(BASE_DIR))
LLM_AGENT_ENABLED_BUILTIN_TOOLS = _get_env_list(
    "LLM_AGENT_ENABLED_BUILTIN_TOOLS",
    ["glob", "grep", "list_dir", "read_file"],
)
LLM_AGENT_ENABLE_SUBAGENTS = _get_env_bool("LLM_AGENT_ENABLE_SUBAGENTS", True)
LLM_AGENT_MAX_TOOL_ROUNDS = _get_env_int("LLM_AGENT_MAX_TOOL_ROUNDS", 4)
LLM_AGENT_MAX_SUBAGENT_TOOL_ROUNDS = _get_env_int("LLM_AGENT_MAX_SUBAGENT_TOOL_ROUNDS", 4)
LLM_AGENT_MAX_TOOL_RESULT_CHARS = _get_env_int("LLM_AGENT_MAX_TOOL_RESULT_CHARS", 120000)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "zh-hans")

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "AI4MW_web.social_adapter.AutoConnectSocialAccountAdapter"

SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_PROVIDERS = {
    "github": {
        "SCOPE": ["read:user", "user:email"],
    }
}

SESSION_COOKIE_AGE = 900

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": True,
        },
        "allauth": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "llm_agent": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
